# Hexo site configuration
title: dreaveler's Homepage
subtitle: PKU AI undergraduate sharing notes and project writeups.
description: PKU AI undergraduate sharing notes and project writeups.
keywords:
  - PKU
  - AI
  - course notes
  - embodied AI
author: dreaveler
language: zh-CN
timezone: Asia/Shanghai

url: https://dreaveler.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - net2/**

new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js

theme: fluid

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false

prismjs:
  enable: false

markdown:
  preset: default
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: false
    quotes: "“”‘’"
  plugins:
    - "@traptitech/markdown-it-katex"

index_generator:
  path: ""
  per_page: 10
  order_by: -date

per_page: 10
pagination_dir: page

search:
  path: local-search.xml
  field: all
  content: true

sitemap:
  path: sitemap.xml
